Repository googleapis/teeny-request, pull requests merged in 2020-06, with the labels that each got.

#173 chore(docs): update badge link in README
  README.md
Labels: cla: yes

#176 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#178 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#179 docs: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: cla: yes, context: full

#180 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
