Repository googleapis/teeny-request, pull requests merged in 2020-07, with the labels that each got.

#182 chore(deps): upgrade nock to v13
  package.json
  test/index.ts
Labels: cla: yes

#183 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#184 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#186 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#187 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#188 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: none

#189 build: rename __toc to toc, add config files for cloud-rad, delete template for Node 8 tests, add missing closing parenthesis in publish script
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#190 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#191 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: cla: yes, context: full
