Repository googleapis/teeny-request, pull requests merged in 2021-05, with the labels that each got.

#222 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#224 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#223 fix: Buffer is allow as body without encoding to string
  src/index.ts
Labels: cla: yes

#226 tests: improve test coverage for request body
  test/index.ts
Labels: cla: yes

#227 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  owlbot.py
  synth.metadata
  synth.py
Labels: cla: yes
